// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glqtizmabvinrcsdwdxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscXRpem1hYnZpbnJjc2R3ZHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTAyNTcsImV4cCI6MjA2NzQyNjI1N30.wh90E4afuzu5ig13lD7Ez5qYpbpmc5h0VekmGp_EMYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});